/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FundRequest {
  'id' : bigint,
  'utr' : string,
  'status' : FundRequestStatus,
  'user' : Principal,
  'timestamp' : Time,
  'amount' : bigint,
}
export type FundRequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Order {
  'id' : bigint,
  'service' : Service,
  'status' : OrderStatus,
  'link' : string,
  'user' : Principal,
  'timestamp' : Time,
  'amount' : bigint,
}
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'processing' : null };
export type Service = { 'repost' : null } |
  { 'likes1k' : null } |
  { 'views10k' : null } |
  { 'followers10k' : null } |
  { 'comments100' : null } |
  { 'followers1k' : null };
export type Time = bigint;
export interface UserProfile { 'balance' : bigint, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUser' : ActorMethod<[string], undefined>,
  'getAllFundRequests' : ActorMethod<[], Array<FundRequest>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getBalance' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFundRequestHistory' : ActorMethod<[], Array<FundRequest>>,
  'getOrderHistory' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[Service, string], undefined>,
  'processFundRequest' : ActorMethod<[bigint, boolean], undefined>,
  'requestFunds' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];