/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FundRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const FundRequest = IDL.Record({
  'id' : IDL.Nat,
  'utr' : IDL.Text,
  'status' : FundRequestStatus,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Int,
});
export const Service = IDL.Variant({
  'repost' : IDL.Null,
  'likes1k' : IDL.Null,
  'views10k' : IDL.Null,
  'followers10k' : IDL.Null,
  'comments100' : IDL.Null,
  'followers1k' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'service' : Service,
  'status' : OrderStatus,
  'link' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'balance' : IDL.Int,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUser' : IDL.Func([IDL.Text], [], []),
  'getAllFundRequests' : IDL.Func([], [IDL.Vec(FundRequest)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getBalance' : IDL.Func([], [IDL.Int], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFundRequestHistory' : IDL.Func([], [IDL.Vec(FundRequest)], ['query']),
  'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([Service, IDL.Text], [], []),
  'processFundRequest' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'requestFunds' : IDL.Func([IDL.Int, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FundRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const FundRequest = IDL.Record({
    'id' : IDL.Nat,
    'utr' : IDL.Text,
    'status' : FundRequestStatus,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Int,
  });
  const Service = IDL.Variant({
    'repost' : IDL.Null,
    'likes1k' : IDL.Null,
    'views10k' : IDL.Null,
    'followers10k' : IDL.Null,
    'comments100' : IDL.Null,
    'followers1k' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'service' : Service,
    'status' : OrderStatus,
    'link' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'balance' : IDL.Int, 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUser' : IDL.Func([IDL.Text], [], []),
    'getAllFundRequests' : IDL.Func([], [IDL.Vec(FundRequest)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getBalance' : IDL.Func([], [IDL.Int], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFundRequestHistory' : IDL.Func([], [IDL.Vec(FundRequest)], ['query']),
    'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([Service, IDL.Text], [], []),
    'processFundRequest' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'requestFunds' : IDL.Func([IDL.Int, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };